version: "3.9"

services:
  db:
    image: postgres:16
    container_name: contora_db
    restart: always
    env_file:
      - .env-copy

  bot-app:
    image: contora
    container_name: contorabot
    build:
      context: .
    env_file:
      - .env-copy
    restart: always
    depends_on:
      - db
    command: sh -c "alembic upgrade head && python bot.py"

