services:
  db:
    image: postgres:16
    container_name: contora_db
    restart: always
    env_file:
      - .env-copy

  bot-app:
    image: contora
    container_name: contorabot
    build:
      context: .
    env_file:
      - .env-copy
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    command: sh -c "alembic upgrade head && python bot.py "

  admin:
    image: admincontora
    container_name: adminbot
    build: .
    env_file:
      - .env-copy
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
