version: '3.8'

services:
  db:
    image: postgres:16
    container_name: contoradb
    environment:
      - DB_HOST=localhost
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=poizoncontora
  bot-app:
    container_name: contorabot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["python", "./bot.py"]
    depends_on:
      - db
