version: '3.8'

services:
  db:
    image: postgres:16
    container_name: contora_db
    restart: always
    env_file:
      - .env-copy
    volumes:
      - db_data:/var/lib/postgresql/data

  bot-app:
    image: contora
    container_name: contorabot
    build:
      context: .
    env_file:
      - .env-copy
    restart: always
    depends_on:
      - db
    ports:
      - "90:90"
    command: sh -c "alembic upgrade head && python bot.py "

  admin:
    image: admincontora
    container_name: adminbot
    build: .
    env_file:
      - .env-copy
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - admin

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
