class StaticFile():
    # Тесты

    # # Cтарт
    photo_url_start = "AgACAgIAAxkBAAIKH2X8CRE8oPb1aTTXwai4fykIeoiZAAIp0TEbe3LhS1dSKGLqlMocAQADAgADeQADNAQ"

    # # Калькулятор
    photo_url_rate_1 = "AgACAgIAAxkBAAIKbWX8D5CcFilHbucVRtzQ4x1A1IF8AAJB0TEbe3LhSwPYwnyIeur1AQADAgADeQADNAQ"
    photo_url_rate_2 = "AgACAgIAAxkBAAIKb2X8D6SYkE-0BelovusxTUi9IZEFAAJD0TEbe3LhS3Ue4z9hLAEPAQADAgADeAADNAQ"

    # # Гайд
    poizon_1 = "AgACAgIAAxkBAAIF0WX4QXGjXGClZFUMibdi6EDY2fa7AAKq2DEbqmHBS1HF-QsGuptdAQADAgADeAADNAQ"
    poizon_2 = "AgACAgIAAxkBAAIF02X4QX8b5ZnIj0GTssP5wrign5WcAAKr2DEbqmHBS1FXs-L4SH4BAQADAgADeAADNAQ"
    poizon_3 = "AgACAgIAAxkBAAIF1WX4QYihzlZAuuROs2ufNNoU9A_SAAKs2DEbqmHBS9e_z3SWAXV6AQADAgADeAADNAQ"
    poizon_4 = "AgACAgIAAxkBAAIF12X4QZS6av8nogXwgXo3bULzYfu5AAKt2DEbqmHBS5SHlzp0NjoFAQADAgADeAADNAQ"
    poizon_5 = "AgACAgIAAxkBAAIF2WX4QaCAYDPCsxnlRyeYgYKU7pP5AAKz2DEbqmHBSwnsyj0ak911AQADAgADeAADNAQ"
    poizon_6 = "AgACAgIAAxkBAAIF22X4QiQeazLwa4v6J-OP_p76Jw_9AAK62DEbqmHBS2sEYMMRxwmfAQADAgADeAADNAQ"
    poizon_7 = "AgACAgIAAxkBAAIF3WX4Qi-Y2kjwuz4j0yPj6ZAN028aAAK72DEbqmHBS68VhcwNLReIAQADAgADeAADNAQ"
    poizon_8 = "AgACAgIAAxkBAAIF32X4QkBvRVCDiYnat_50PtoeVAgIAAK92DEbqmHBS_dy7dZahgIaAQADAgADeAADNAQ"
    poizon_9 = "AgACAgIAAxkBAAIF4WX4QlK3YBIRcSUZw0RM49AX5JGCAALD2DEbqmHBS8FMOok-MMZEAQADAgADeAADNAQ"

    file_1 = "BQACAgIAAxkBAAIJUGX6uuLQ27eWxWLFtqbKjhO0P3POAAKDQAACd-PZS1PCpnS08OK1NAQ"

    register_guide = "AgACAgIAAxkBAAIGnGX5Q4KOoCMtcAHifOvqu9AItSnSAAIT2DEbqmHJS0BUzaSM8VVvAQADAgADeQADNAQ"

    register_guide_1 = "AgACAgIAAxkBAAIEP2X3_2De7kr1o0-b9QmGitbZqmEzAAIF1DEbYA3AS9apwqfRgmQLAQADAgADeQADNAQ"
    register_guide_2 = "AgACAgIAAxkBAAIEO2X3_1cSZyZ-6FBKHmExuEOOnmChAAID1DEbYA3AS5MHY30bEBBiAQADAgADeQADNAQ"
    register_guide_3 = "AgACAgIAAxkBAAIEPWX3_10Fjin1XG2y8vuhlWkC6FBfAAIE1DEbYA3AS9s2FDkXDNA2AQADAgADeQADNAQ"

    search_guide_1 = "AgACAgIAAxkBAAIElWX4GbV-b-HFiDyu0GdTYMeq7qARAAKl1DEbYA3AS0XbaPpbHVLeAQADAgADeQADNAQ"
    search_guide_2 = "AgACAgIAAxkBAAIEl2X4Gb1bIdEBKipO25XTBAt40WKZAAKm1DEbYA3AS5tw0opCUYQ1AQADAgADeQADNAQ"
    search_guide_3 = "AgACAgIAAxkBAAIEmWX4GcUG2LSlHU8z3e6fYcQ0a52QAAKn1DEbYA3AS3tOcY5JF45HAQADAgADeQADNAQ"
    search_guide_4 = "AgACAgIAAxkBAAIEm2X4Gc1ueSBMOt1ziS8SO5uBa2ZIAAKo1DEbYA3AS70ygdlnvMr0AQADAgADeQADNAQ"
    search_guide_5 = "AgACAgIAAxkBAAIEnWX4GdICLFRCHM7q7G0wO7JOoh0gAAKp1DEbYA3AS0nvlWJkmXMCAQADAgADeQADNAQ"

    size_guide_1 = "AgACAgIAAxkBAAIEm2X4Gc1ueSBMOt1ziS8SO5uBa2ZIAAKo1DEbYA3AS70ygdlnvMr0AQADAgADeQADNAQ"
    size_guide_2 = "AgACAgIAAxkBAAIFAAFl-CVjqtRgLFQN6CkhMa3jNSawnwAC6tQxG2ANwEtxAxwUsxI5_QEAAwIAA3kAAzQE"
    size_guide_3 = "AgACAgIAAxkBAAIFAmX4JWf-iJeFM9P_jbrXXFVmInD6AALr1DEbYA3ASzKjpP7Q-elbAQADAgADeQADNAQ"

    url_guide_1 = "AgACAgIAAxkBAAIFWWX4NLPdzOeI5ifSuzJrBhzlSr0TAAI32DEbqmHBSw_W6hXsx-scAQADAgADeQADNAQ"
    url_guide_2 = "AgACAgIAAxkBAAIFW2X4NLcUAAG-JuRUMUlWhmtl16BHAgACONgxG6phwUtkfyLCRxI_5QEAAwIAA3kAAzQE"

    # # Заказ
    url_order = "AgACAgIAAxkBAAIKf2X8Fdc1eE27voRENWP71w3GYuV8AAJX0TEbe3LhS4li6XE52cMyAQADAgADeAADNAQ"

    video = "BAACAgIAAxkBAAIuBGZdnOLeIM9c8YiQ1f2E8bGPeBm3AALKRwACIy7xSlFZdR-2VCRwNQQ"

    # # сервер

    # # #Cтарт
    # photo_url_start = "AgACAgIAAxkBAAIOfGX8EAK-sFTw15R-ftvAmRUdkKi9AAIp0TEbe3LhS_MNUc6vRYd0AQADAgADeQADNAQ"

    # # Калькулятор
    # photo_url_rate_1 = "AgACAgIAAxkBAAIOfmX8EBJIqht5EDqwNMfhPBlR2REFAAJB0TEbe3LhSyCQKLJLYjrAAQADAgADeQADNAQ"
    # photo_url_rate_2 = "AgACAgIAAxkBAAIOgGX8EB3E6syG8AABdGayhDhmMGXFdgACQ9ExG3ty4Ut50XO-VO3C1QEAAwIAA3gAAzQE"

    # # Гайд
    # poizon_1 = "AgACAgIAAxkBAAII1GX0MesrJHO8mL_H-QSrfc0RwXYKAAIH2DEbvlagS0qUe8WK0MttAQADAgADeAADNAQ"
    # poizon_2 = "AgACAgIAAxkBAAII1mX0MfLvXlMQEn75grUDSRHxkQ9kAAId2DEbvlagS23cyonH1o8pAQADAgADeAADNAQ"
    # poizon_3 = "AgACAgIAAxkBAAII2GX0MfbeifqYKj15dWWPK9jcmJdLAAIe2DEbvlagS6l_SugOyr5LAQADAgADeAADNAQ"
    # poizon_4 = "AgACAgIAAxkBAAII2mX0Mfxy_BIp2mTs7ldfX6XJvXbUAAIf2DEbvlagS57cStXrdazOAQADAgADeAADNAQ"
    # poizon_5 = "AgACAgIAAxkBAAII3GX0MgABBGw_2bmXv-zh15R1_ranaQACINgxG75WoEuVE2MQAAGt-PcBAAMCAAN4AAM0BA"
    # poizon_6 = "AgACAgIAAxkBAAII3mX0MgSY2VPJPKGK1TXdqgcvsLU9AAIh2DEbvlagS2skqmQ3bWjbAQADAgADeAADNAQ"
    # poizon_7 = "AgACAgIAAxkBAAII4GX0MglNa2FOOOgy1dVyHD7qTB-ZAAIi2DEbvlagS6uux6No-IYTAQADAgADeAADNAQ"
    # poizon_8 = "AgACAgIAAxkBAAII4mX0Mg2BrpzXQi6laXcKi43HfJyRAAIj2DEbvlagS7tH_qxWmIZpAQADAgADeAADNAQ"
    # poizon_9 = "AgACAgIAAxkBAAII5GX0MhE8xZRWYlksMlRjmhkGaQTKAAIk2DEbvlagS_HhVQeHkDiYAQADAgADeAADNAQ"

    # file_1 = "BQACAgIAAxkBAAIJF2X0Q25XzC9d3Scln9zmao5kjw4zAALPRAACvlagS-VCxk9phw4TNAQ"

    # register_guide = "AgACAgIAAxkBAAIM6WX6vStGenN6nH5AAg6vadTJzdg2AAI61TEbELrYS1lNEoHG-ZQqAQADAgADeQADNAQ"

    # register_guide_1 = "AgACAgIAAxkBAAIKumX4NsDLBfOKOW2x9ntuk8LYQlopAALQ3jEb9HzAS2LeQ3ppIK1zAQADAgADeQADNAQ"
    # register_guide_2 = "AgACAgIAAxkBAAIKvGX4Ns1ySv7gsQ3ArNjpkAP_du4oAALR3jEb9HzAS3bsmAvjVhmMAQADAgADeQADNAQ"
    # register_guide_3 = "AgACAgIAAxkBAAIKvmX4Nt1e9ZC2WrW9zTPgb-se1_QBAALS3jEb9HzAS494kVWnDjnGAQADAgADeQADNAQ"

    # search_guide_1 = "AgACAgIAAxkBAAIKwGX4NxJ3svDuFu0VlRT5_9EhfEz8AAKl1DEbYA3AS48OJ_ngE9MAAQEAAwIAA3kAAzQE"
    # search_guide_2 = "AgACAgIAAxkBAAIKwmX4NyDhugrh_XzDEUKdV0DOjFPnAAKm1DEbYA3AS4LiikIM5RpTAQADAgADeQADNAQ"
    # search_guide_3 = "AgACAgIAAxkBAAIKxGX4NzCTAAGyzks68uhvmcMAAS0G49YAAqfUMRtgDcBLfcFliyhu7AQBAAMCAAN5AAM0BA"
    # search_guide_4 = "AgACAgIAAxkBAAIKxmX4N0HtF-FSVB28RHjwG4jAHablAAKo1DEbYA3AS4yfDR7ZcuiqAQADAgADeQADNAQ"
    # search_guide_5 = "AgACAgIAAxkBAAIKyGX4N06cIviK_aTaEdrdnjpU6VscAAKp1DEbYA3AS2S9FatVih6hAQADAgADeQADNAQ"

    # size_guide_1 = "AgACAgIAAxkBAAIKxmX4N0HtF-FSVB28RHjwG4jAHablAAKo1DEbYA3AS4yfDR7ZcuiqAQADAgADeQADNAQ"
    # size_guide_2 = "AgACAgIAAxkBAAIKymX4N5Rm1QZSi3auGOtnzdbjChrSAALq1DEbYA3AS9mnqnG84b6mAQADAgADeQADNAQ"
    # size_guide_3 = "AgACAgIAAxkBAAIKzGX4N56DOujCiocgtL3WSt134-_pAALr1DEbYA3AS_wE3pW_dbGLAQADAgADeQADNAQ"

    # url_guide_1 = "AgACAgIAAxkBAAIKzmX4N82PI6w54wHGTBfpeuRkJ44mAAI32DEbqmHBSwkV6ldJ4mDLAQADAgADeQADNAQ"
    # url_guide_2 = "AgACAgIAAxkBAAIK0GX4N9bMpLDhPeZh7_ymQ0x3XQTUAAI42DEbqmHBS0cdyE8mvgg8AQADAgADeQADNAQ"
    # # Заказ
    # url_order = "AgACAgIAAxkBAAIOx2X8FgryrpDMsQqzR1dIS0sOdJagAAJX0TEbe3LhS_mrT9iq2rGQAQADAgADeAADNAQ"

    # video = "BAACAgIAAxkBAAIuBGZdnOLeIM9c8YiQ1f2E8bGPeBm3AALKRwACIy7xSlFZdR-2VCRwNQQ"


static = StaticFile()
