# Generated by Django 5.0.3 on 2024-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderGivenModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('addres', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'given_order',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
